# source bash_aliases at login / shell
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# change bash PS1 styling on login / shell
# https://dom.hastin.gs/files/bash-ps1/
export PS1='\[\033[49;38;5;74m\]\u\[\033[49;38;5;104m\]@\[\033[49;38;5;74m\]\h\[\033[49;38;5;104m\]:[\[\033[49;38;5;173m\]\W\[\033[49;38;5;104m\]]$ \[\033[49;39m\]';

# source bash_paths at login / shell
if [ -f ~/.bash_paths ]; then
   source ~/.bash_paths
fi
