# source bash_aliases at login / shell
if [ -f ~/.bash_aliases ]; then
        . ~/.bash_aliases
      fi

# save default PS1 just in case
DEFAULT=$PS1

# change bash PS1 styling
export PS1='\[\033[49;38;5;74m\]\u\[\033[49;38;5;104m\]@\[\033[49;38;5;74m\]\h\[\033[49;38;5;104m\]:[\[\033[49;38;5;173m\]\W\[\033[49;38;5;104m\]]$ \[\033[49;39m\]';
