# Colorize the ls output
alias ls='ls --color=auto -h'

# Use a long listing format
alias ll='ls -lah'

# Show hidden files
alias l.='ls -dh .* --color=auto'

# Colorize the grep command output for ease of use (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# These next few help stop the students from accidents
# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'

# confirmation
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

# this one saved my butt so many times
alias wget='wget -c'

# google chrome
alias chrome='/opt/google/chrome/chrome'

# stop bash from caching duplicate lines
HISTCONTROL=ignoredups

# disk free in human terms
alias df='df -h'

# source
alias reload='source $HOME/.bashrc'

# head/tail short
alias h='head'
alias t='tail'
